spring:
  profiles:
    active:
      - dev      
---
server:
  port: 8001
  
spring:
  profiles: dev #开发环境
  application:
    name:  microserivce-dept  #微服务对外曝光的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #使用阿里云的连接池
    driver-class-name: com.mysql.cj.jdbc.Driver  #mysql的驱动包
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false  #链接 的数据库
    username: root
    password: 1111
    dbcp2:
      min-idle:  6   #当前数据库连接池的最小连接数
      initial-size:  6   #初始化的连接
      max-idle:  6   #最大的连接数
      max-wait-millis: 200 #获取连接最大的超时时间
      
mybatis:
  config-location:  classpath:mybatis/mybatis.cfg.xml  #mybatis配置的文件路径
  type-aliases-package:  com.spring.cloud.entity   #所有的实体类
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  #mapper映射的文件
   
eureka: 
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #需要与eureka注册中心的地址一致 # 配置将8001发布到Eureka集群配置中  8001中有7001
  instance: 
    instance-id:  microserivce-dept-8001-hystrix #别名 主机映射名称修改
    prefer-ip-address: true   #开启Ip 访问路径显示IP地址
    
info: #追加微服务信息的描述
  app.name: microserivce-dept #工程的名称
  company.name: www.service.com   #公司的名称
  build.artifactId: $project.artifactId$ #灵活调用在父工程有配置build
  build.version: $project.version$
   
---

server:
  port: 8001

spring:
  profiles: test #测试环境
  application:
    name:  microserivce-dept  #微服务对外曝光的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #使用阿里云的连接池
    driver-class-name: com.mysql.cj.jdbc.Driver  #mysql的驱动包
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false  #链接 的数据库
    username: root
    password: 1111
    dbcp2:
      min-idle:  6   #当前数据库连接池的最小连接数
      initial-size:  6   #初始化的连接
      max-idle:  6   #最大的连接数
      max-wait-millis: 200 #获取连接最大的超时时间
      
mybatis:
  config-location:  classpath:mybatis/mybatis.cfg.xml  #mybatis配置的文件路径
  type-aliases-package:  com.spring.cloud.entity   #所有的实体类
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  #mapper映射的文件
   
eureka: 
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #需要与eureka注册中心的地址一致 # 配置将8001发布到Eureka集群配置中  8001中有7001
  instance: 
    instance-id:  microserivce-dept-8001-hystrix #别名 主机映射名称修改
    prefer-ip-address: true   #开启Ip 访问路径显示IP地址
    
info: #追加微服务信息的描述
  app.name: microserivce-dept #工程的名称
  company.name: www.service.com   #公司的名称
  build.artifactId: $project.artifactId$ #灵活调用在父工程有配置build
  build.version: $project.version$