spring:
  profiles:
    active:
      - dev      
---
server:
  port: 7001

spring:
  profiles: dev #开发环境
  application:
    name: servicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #eureka server的实例名称  #    hostname: localhost#eureka7001.com  #eureka server的实例名称
  client:
    register-with-eureka: false #不将本身注入注册中心
    fetch-registry: false #表示自身端就是一个注册中心.就是进行维护服务实例，不需要进行检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/# 开启eureka集群配置 7001中有7002和7003
 
---

server:
  port: 7001

spring:
  profiles: test #测试环境
  application:
    name: servicecloud-config-client

eureka:
  instance:
    hostname: eureka7001.com #eureka server的实例名称  #    hostname: localhost#eureka7001.com  #eureka server的实例名称
  client:
    register-with-eureka: false #不将本身注入注册中心
    fetch-registry: false #表示自身端就是一个注册中心.就是进行维护服务实例，不需要进行检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/# 开启eureka集群配置 7001中有7002和7003
 